language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sphinx-docs' ]; then cd .. && eval "mv $currentfolder generator-sphinx-docs" && cd generator-sphinx-docs; fi

